### PR TITLE
urlKey and cookieKey options

### PR DESCRIPTION
**Pull request by dherault**
Hi,

This PR allows to specify a custom URL parameter or cookie key for passing the JWT.

```javascript
server.auth.strategy('jwt', 'jwt', true,
    { key: 'NeverShareYourSecret',          // Never Share your secret key
      validateFunc: validate,            // validate function defined above
      verifyOptions: { algorithms: [ 'HS256' ] }, // pick a strong algorithm
      urlKey: 'customKeysAreCool', // now one can request http://foo.bar/customKeysAreCool=j.w.t
      cookieKey: 'imCustomToo' // cookie : imCustomToo=j.w.t
    });
```

It still defaults to `token`. I updated the readme as well.
Hope this can be useful.

### CODE REVIEW

**Comment by nelsonic** [comment]
@dherault seems like a good addition. 
however, to accept the PR we need the tests to be updated to achieve 100% coverage:

hapi-auth-jwt2-insufficient-coverage

Please create additional tests to ensure we have 100% branch coverage.
Specifically these lines:

hapi-auth-jwt2-branch-coverage

**Comment by dherault** [comment]
@nelsonic Done, 100%!

**Comment by nelsonic** [comment]
@dherault thanks!
hapi-auth-jwt2-pr-test-coverage

@iteles I have code-reviewed.
Please second-pair-of-eyes and merge. Thanks! :+1:

**Comment by iteles** [comment]
Looks great, thanks @dherault

**Comment by gilly3** [comment]
I want this... When will you update NPM?

**Comment by nelsonic** [comment]
@gilly3 & @dherault Please update your `package.json` to `4.9.0` :+1: 
@gilly3 you've been invited to join [***dwyl***](https://github.com/dwyl)
please :star: this repo to signal to others that you find this plugin useful.
Thanks!

**Pull request merged**
