### PR TITLE
Move check for authorization header up in the logic stack

### PR DESCRIPTION
**Pull request by duro**
This may not quite fix the problem entirely mention in #65, but I think it's a start.

The final fix would be to also somehow use a regex to confirm not only that a cookie is present, but that the token actually exists in it.

I'm just not super familiar with the full scope of what cookies with a bunch of junk in them look like to write that RegEx

### CODE REVIEW

**Comment by nelsonic** [comment]
@duro moving the Auth Header check up the stack will definitely _ameliorate_ the situation in the short run, please also increase the node module version number to `4.7.1` in `package.json` and commit to your branch so I can merge this in and publish the patch to NPM. :+1:

**Comment by duro** [comment]
Done and done

**Comment by nelsonic** [comment]
Thanks @duro :+1:

**Comment by nelsonic** [comment]
Published 4.7.1 to NPM. 
You will need to update *your* `package.json` with the command `npm i hapi-auth-jwt2@4.7.1 --save`
Thanks again for informing us and submitting the issue/PR! 
fixes #65

**Pull request merged**
