### PR TITLE
Fix url

### PR DESCRIPTION
**Pull request by kevinsimper**
The url was wrong, so if you tried to go from npmjs.com then 404

### CODE REVIEW

**Comment by iteles** [comment]
Hey @kevinsimper, thanks for submitting this PR!
Are you able to make the changes required so that the Travis build passes?

**Comment by kevinsimper** [comment]
It is not something I can fix, it is an error in io.js.

**Comment by nelsonic** [comment]
Looks like the fix has been applied to io.js but might not be on Travis-CI yet...

**Comment by nelsonic** [comment]
I'm satisfied that this is working on Node.js v.0.10 & v0.12 which are the ones ***most people*** are using. @iteles lets merge this! thanks!

**Comment by nelsonic** [comment]
thanks @kevinsimper :+1:

**Comment by iteles** [comment]
:+1: Thanks!

**Pull request merged**
