### PR TITLE
feat: add Typescript types

### PR DESCRIPTION
**Pull request by jaulz**
Let me know if anything else is required 😊

### CODE REVIEW

**Comment by nelsonic** [comment]
@jaulz `hapi-auth-jwt2@8.6.1` on NPM contains this update. thanks again. 👍

**Comment by jaulz** [comment]
@nelsonic cool, thanks 😊

**Comment by xpolb01** [comment]
@jaulz Please revert as it is breaking previous versions. See https://github.com/dwyl/hapi-auth-jwt2/issues/310#issuecomment-501381850

**Comment by nelsonic** [comment]
@xpolb01 NPM does not allow reverting. We can _fix_ the type specs and publish a `new` version.

**Pull request merged**
