### PR TITLE
V10.4.0

### PR DESCRIPTION
**Pull request by nelsonic**
This PR creates a new [maintenance] release for the package. 📦 
To publish a version with the updated `jsonwebtoken` dependency https://github.com/dwyl/hapi-auth-jwt2/pull/374 ⬆️ 

Changelog:

```md
# Version 10.3.0 - Security Update to `jsonwebtoken` Dependency

Update version of `jsonwebtoken` dependency to latest
to avoid security issues. 
See: https://github.com/dwyl/hapi-auth-jwt2/pull/374 thanks @AntoineAA 
More detail in: https://github.com/dwyl/hapi-auth-jwt2/pull/373 thanks Snyk. 
```

Sadly the deps badges are no longer working: 
[Dependencies Status](https://david-dm.org/dwyl/hapi-auth-jwt2)
[devDependencies Status](https://david-dm.org/dwyl/hapi-auth-jwt2?type=dev)

Removing from `README.md` ✂️ 

Also:

+ [x] Replaces `.travis.yml` with `.github` (GitHub Actions/CI + @dependabot)
+ [x] Update version of `prettier` + `eslint` to latest and updates code in `index.js` from `function` to `=>` ... 🙄 https://github.com/dwyl/hapi-auth-jwt2/pull/375#issuecomment-1371859575
+ [x] Updates `README.md` badges from `master` to `main`

### CODE REVIEW

**Comment by nelsonic** [comment]
@snyk finds 4 issues with this PR, all `jsonwebtoken`:
image

Thanks @snyk, _suuuuuuuper_ helpful. Thanks for failing the build that releases the new version of the package to fix the problem you've identified. 🎉

**Comment by nelsonic** [comment]
Meanwhile what I _really_ want is to know if the CI (GitHub Actions) is passing so I know if `Hapi@v21` works ... 🤷‍♂️

**Comment by nelsonic** [comment]
OK. I'm `done` with @snyk between them creating a PR _as_ me #373 🤦‍♂️ 
and now prematurely failing this build that is updating the issue they have identified ... `done`. 🙅

**Comment by nelsonic** [comment]
What kind of security system allows a **_manual_ override**? 🤦‍♂️ 
https://app.snyk.io/org/nelsonic/pr-checks/2af9b479-c08f-4551-8e13-e0815297bc90
snyk-manual-overrid

This is an acknowledgement that their system is fundamentally broken. 💔

**Comment by nelsonic** [comment]
"Mark as successful" indeed ...
image

**Comment by nelsonic** [comment]
Attempted to run `npm audit fix` ... got:

```sh
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: eslint-plugin-prettier@3.1.3
npm ERR! Found: eslint@7.0.0-rc.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^7.0.0-alpha.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@">= 5.0.0" from eslint-plugin-prettier@3.1.3
npm ERR! node_modules/eslint-plugin-prettier
npm ERR!   dev eslint-plugin-prettier@"^3.1.2" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: eslint@8.31.0
npm ERR! node_modules/eslint
npm ERR!   peer eslint@">= 5.0.0" from eslint-plugin-prettier@3.1.3
npm ERR!   node_modules/eslint-plugin-prettier
npm ERR!     dev eslint-plugin-prettier@"^3.1.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by nelsonic** [comment]
Gonna try and _manually_ update `eslint` and `prettier` ... 🧑‍💻⏳ 🙄

**Comment by nelsonic** [comment]
Somewhat predictably ...

```sh
npm run lint

> hapi-auth-jwt2@10.3.0 lint
> eslint lib


/Users/n/code/hapi-auth-jwt2/lib/index.js
   20:21  error  Insert `·`                                                                                                                                         prettier/prettier
   46:37  error  Insert `·`                                                                                                                                         prettier/prettier
   56:32  error  Insert `·`                                                                                                                                         prettier/prettier
   64:35  error  Insert `·`                                                                                                                                         prettier/prettier
   73:31  error  Insert `·`                                                                                                                                         prettier/prettier
   85:40  error  Insert `·`                                                                                                                                         prettier/prettier
  184:12  error  Replace `⏎········isValid,⏎········credentials,⏎········response,⏎········errorMessage,` with `·isValid,·credentials,·response,·errorMessage·}·=`  prettier/prettier
  189:7   error  Replace `}·=` with `·`                                                                                                                             prettier/prettier
  324:36  error  Insert `·`                                                                                                                                         prettier/prettier
  340:33  error  Insert `·`                                                                                                                                         prettier/prettier
  371:28  error  Insert `·`                                                                                                                                         prettier/prettier
  402:23  error  Insert `·`                                                                                                                                         prettier/prettier
  410:20  error  Replace `err` with `(err)`                                                                                                                         prettier/prettier
  424:27  error  Insert `·`                                                                                                                                         prettier/prettier

✖ 14 problems (14 errors, 0 warnings)
  14 errors and 0 warnings potentially fixable with the `--fix` option.
```

This is silly.

```sh
20:21  error  Insert `·`    
```

the line in question is: 
https://github.com/dwyl/hapi-auth-jwt2/blob/0cf2b34234d713157c453a1bedcffa8a63695cce/lib/index.js#L20

How does this line need a `.` on it? 🤷‍♂️

**Comment by nelsonic** [comment]
Through a little investigation, 🔍 
it turns out that the latest version of `prettier` doesn't _allow_ the `function` keyword. 🤷‍♂️ 
Everything has to be `=>` (arrow functions) ... 🤦‍♂️ 

Sooooo glad I don't write `JS` anymore. 
This is suuuuper lame! the `function` keyword is perfectly fine!
why do the Küel Kids have to _ruin_ perfectly working code?! 🤦‍♂️

**Comment by nelsonic** [comment]
Much better: 

image

**Comment by nelsonic** [comment]
@SimonLab please take a look and merge when you're back at your desk. Thanks. 🙏

**Review by SimonLab — APPROVED** [review]
Looks good thanks :+1:

**Pull request merged**
