### PR TITLE
fix missing payload validation. see #293

### PR DESCRIPTION
**Pull request by icetbr**
see https://github.com/dwyl/hapi-auth-jwt2/issues/293

### CODE REVIEW

**Comment by icetbr** [comment]
I simplified the logic, don't know for sure if all that code was needed. Please advise if any change is required.

**Comment by icetbr** [comment]
Bump. Can I have a feedback on this one? I tried putting my own version as a dependency, but npm is giving me trouble

**Comment by jasonswearingen** [comment]
@nelsonic plz review

**Comment by nelsonic** [comment]
`hapi-auth-jwt2@8.4.0` on NPM has this update.

**Pull request merged**
