### PR TITLE
linting

### PR DESCRIPTION
**Pull request by manonthemat**
I did some cleanup

### CODE REVIEW

**Comment by edwardcodes** [comment]
Looks good @manonthemat :+1: 
Did you use a tool to do the linting?

**Comment by manonthemat** [comment]
I've noticed some minor things while looking through the latest commits and then used eslint to find missing semi-colons.

**Comment by nelsonic** [comment]
Sweet. :lollipop: 
Merging. :shipit:

**Comment by harriha** [comment]
The project seems to have jshint configured - if those jshint rules didn't catch these issues, shouldn't those rules be fixed? If there's a desire keep the code clean and respect a set of linting rules, I believe they should be present in the `.jshintrc`, otherwise contributors have no way of knowing which linting rules to respect when doing modifications. Also, Travis could check these automatically, maybe fine-tune the commands Travis runs?

**Pull request merged**
