### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by manonthemat**

### CODE REVIEW

**Comment by nelsonic** [comment]
@manonthemat, thanks for the PR. 
Just looking into why the Travis Build is failing...

**Comment by nelsonic** [comment]
@manonthemat so it appears that someone @HapijsHQ decided it was time to use ES6 in the core Hapi.js code so that's why the Travis Build is failing ... 
see: https://travis-ci.org/dwyl/hapi-auth-jwt2/jobs/88555807#L235-L236

Which means that we are *forced* to update our supported version of Node.js in our `.travis.yml` file ...

please open `.travis.yml` on your branch and replace the lines:
```sh
node_js:
  - 0.10
  - 0.12
  - 'iojs-v2.1.0'
```
With:
```sh
node_js:
  - "4.1"
```
And commit that change to GitHub.

*Also*, we need the package's ***version number*** to be increased from `5.1.3` to `5.2.0`  in the `package.json` file.

Thanks. :+1:

**Comment by manonthemat** [comment]
Thanks for the explanation and walkthrough. :+1:

**Comment by nelsonic** [comment]
Boom! We can :shipit:

**Comment by nelsonic** [comment]
Latest version is on NPM: `v5.2.0` thanks again! :+1:

**Pull request merged**
