### PR TITLE
Try mode

### PR DESCRIPTION
**Pull request by nelsonic**
Adds regression test for `try` and `optional` auth modes.
see: https://github.com/dwyl/hapi-auth-jwt2/issues/111
Without the lines:
```js
if (!token && request.auth.mode !== 'required') {		
   return reply.continue({ credentials: {} });		
}
```
it *actually* works *exactly* as expected.
Confirmed by the *master* in: https://github.com/hapijs/hapi/issues/2843

@alanshaw I took the regression tests directly from your branch: https://github.com/alanshaw/hapi-auth-jwt2/commit/736067f8f73bf7388438e399e12050489b9a400c
please `checkout` this branch and confirm it works as expected. 
Thanks. :+1:

### CODE REVIEW

**Comment by nelsonic** [comment]
@alanshaw when you get a chance please confirm this works for you. thanks! :+1:

**Comment by alanshaw** [comment]
LGTM - my tests pass with 5.1.0, fail with 5.1.1 and pass again using this branch.

**Comment by nelsonic** [comment]
@alanshaw can we :ship: this version?

**Comment by alanshaw** [comment]
Please do!

**Comment by nelsonic** [comment]
@iteles this merge has been *approved* by @alanshaw, please review/merge when you get back to your desk and let me know when I can `npm publish`. thanks. :+1:

**Comment by iteles** [comment]
Done! :shipit:

**Comment by nelsonic** [comment]
Shipped. :shipit: :white_check_mark: 
@alanshaw `5.1.2` is on NPM.
Thanks again! :+1:

**Comment by alanshaw** [comment]
plz check your gitter messages

**Comment by nelsonic** [comment]
@alanshaw sec report filed. thanks for the advice. :+1:

**Pull request merged**
